# Usa una imagen base de Node
FROM node:20.16.0-alpine

# Directorio de trabajo
WORKDIR /home/app

# Instala las dependencias usando pnpm
RUN npm install -g npm@10.8.2
RUN npm install -g pnpm

# Copiar archivo pnpm-lock.yaml y package.json antes de instalar
COPY pnpm-lock.yaml ./
COPY package.json ./

# Instalar dependencias con pnpm
RUN pnpm install

# Puerto 3000
EXPOSE 3000

# Comando para correr la aplicación
CMD ["pnpm","dev-exposed"]
