services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "react"
    ports:
      - "3000:3000"
    links: 
      - bd
    volumes:
      - .:/home/app
      - /home/app/node_modules
  
  bd:
    image: postgres
    ports:
      - "27017:27017"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=alakazam
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: